<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-CQUQF6I" failures="1" tests="4" name="Test01" time="55.150" errors="0" timestamp="2022-02-16T16:28:57 IST" skipped="0">
  <testcase classname="Test01" name="test01" time="14.494"/>
  <system-out/>
  <testcase classname="Test01" name="test01" time="13.466"/>
  <system-out/>
  <testcase classname="Test01" name="test01" time="11.591"/>
  <system-out/>
  <testcase classname="Test01" name="test01" time="15.599">
    <failure message="The following asserts failed:
	FAIL// Title is not Matched expected [https://www.oyorooms.com/112501/?checkin=20%2F02%2F2022&amp;checkout=21%2F02%2F2022&amp;guests=3&amp;modal=bookingSummary&amp;rooms=2&amp;rooms_config=2-1_0-2_0&amp;selected_rcid=272950] but found [https://www.oyorooms.com/112501/?checkin=20%2F02%2F2022&amp;checkout=21%2F02%2F2022&amp;rooms=2&amp;guests=3&amp;rooms_config=2-1_0-2_0&amp;selected_rcid=272950]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
FAIL// Title is not Matched expected [https://www.oyorooms.com/112501/?checkin=20%2F02%2F2022&checkout=21%2F02%2F2022&guests=3&modal=bookingSummary&rooms=2&rooms_config=2-1_0-2_0&selected_rcid=272950] but found [https://www.oyorooms.com/112501/?checkin=20%2F02%2F2022&checkout=21%2F02%2F2022&rooms=2&guests=3&rooms_config=2-1_0-2_0&selected_rcid=272950]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at Test01.test01(Test01.java:189)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- test01 -->
  <system-out/>
</testsuite> <!-- Test01 -->
